spring:
  datasource:
    name: dan-lester-9fnv
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://serverless-northeurope.sysp0000.db3.skysql.com:4020/bmo_db
    username: dbpbf13773524
    password: Bd7mTsjOodj8Y|A04Ollg.zG

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: dlsanz.asi@gmail.com
    password: umvm uben yagx msyc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: strict
    context-path: /api/
  port: 8080

chat-bot-key: add-chat-bot-key-here
