spring:
  datasource:
    name: bmo_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bmo_db
    username: root
    password: root

  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: "true"
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: strict
    context-path: /api/
  port: 8080


# NOTE: FOR LOCAL TESTING
# (Change the value with the corresponding metro exp value in the terminal)
allowed:
  origin: http://localhost:3000, exp://192.168.1.7